### PR TITLE
fix(frontend): do not use backend url in <img>

### LINKED ISSUE #2408: Images Not Displaying Correctly in langflow (1.0.5) Docker Container Behind Traefik Proxy
I am trying to implement langflow (1.0.5) as a Docker container protected by the Traefik proxy and managed by Portainer. The installation worked well, and langflow is fully operational. However, the images and icons presented by the service exposed on the Internet refer to "http://localhost:7860/..." and, obviously, they cannot be displayed at end user's browser. Scouring the source code, I saw that the environment variable "BACKEND_URL" (e.g., ) should provide the public URL for the responses coming from the server, but the container ignores this variable and always displays the images as src=localhost:7860...". Does anyone have any tips?

This is my stack entries in portainer
-----------

services:
  langflow:
    image: langflowai/langflow:latest
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      #- LANGFLOW_CONFIG_DIR=/var/lib/langflow # If uncomment this line, langflow crashes---WHY???
      - LANGFLOW_SUPERUSER=<MY-LOGIN>
      - LANGFLOW_SUPERUSER_PASSWORD=<MY-PASS>
      - LANGFLOW_NEW_USER_IS_ACTIVE=true
      #- LANGFLOW_SECRET_KEY= # I prefer to fill from the application
      - LANGFLOW_AUTO_LOGIN=false
      - LANGFLOW_HOST=0.0.0.0
      - BACKEND_URL=<https://langflow.my-domain.com/> # Always put the slash '/' at the end
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.langflow.rule=Host(`<https://langflow.my-domain.com>`)" # My public FDN
      - "traefik.http.routers.langflow.entrypoints=web,websecure"
      - "traefik.http.routers.langflow.tls.certresolver=cloudflare"
      - "traefik.http.services.langflow.loadbalancer.server.port=7860"
 
    volumes:
      - langflow-data:/var/lib/langflow

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    ports:
      - "5432:5432"
    volumes:
      - langflow-postgres:/var/lib/postgresql/data
  
volumes:
  langflow-postgres:
  langflow-data:

networks:
  default:
    name: langflow
    external: false

### PR DESCRIPTION
**Pull request by nicoloboschi**
There's already a redirect in place for api calls. 
This affect the user profile and the file react component in general 

Fixes #2408

### CODE REVIEW

File: src/frontend/src/components/headerComponent/index.tsx [hunk 1]
```diff
@@ -50,11 +49,9 @@ export default function Header(): JSX.Element {
   const routeHistory = useLocationStore((state) => state.routeHistory);
 
   const profileImageUrl =
-    `${BACKEND_URL.slice(
-      0,
-      BACKEND_URL.length - 1,
-    )}${BASE_URL_API}files/profile_pictures/${userData?.profile_image}` ??
-    profileCircle;
+    `${BASE_URL_API}files/profile_pictures/${
```
Comment (Cristhianzl) [inline src/frontend/src/components/headerComponent/index.tsx:52]: Hi @nicoloboschi,

I appreciate the refactor that removes the code from the src tag in the HTML. These kind of refactor are always very welcome. 

I just wanted to provide some context and ask a question regarding the variable BACKEND_URL.
This variable was created because Langflow's frontend and backend do not always run on the same server URL. Hence, BACKEND_URL was introduced to handle this scenario.
If we revert to using BASE_URL_API, do you think it might break this setup? What are your thoughts?

Comment (nicoloboschi) [reply src/frontend/src/components/headerComponent/index.tsx:52]: Hey @Cristhianzl 
the scenario is exactly that one, backend and frontend as separate service.
Removing the host will make the browser to reuse the same base host of the current webpage. 

since this is an API call the correct flow is:
- call <frontend_service>/api/....
- The frontend redirects the call to the backend (as it does for other calls)

I've verified the fix with different ports/host for backend and frontend and it works well.

Comment (Cristhianzl) [reply src/frontend/src/components/headerComponent/index.tsx:52]: Awesome, I will trust in you in that case hahah
Thanks for your explanation and reply!

LGTM

**Review by Cristhianzl — APPROVED** [review]
